#!/usr/bin/env python
"""
custom_team_wrapper.py
----------------------

Expose an AutoGen‑Studio *team* as a REST endpoint whose name
you can choose, and load secrets from any .env file.

EXAMPLE
    $ python custom_team_wrapper.py serve \
          team.json \
          --endpoint /peak-research \
          --env-file ~/.config/ags/prod.env \
          --port 8080
"""

from pathlib import Path
import os
import typer
import warnings 
from dotenv import load_dotenv
from fastapi import FastAPI
from pydantic import BaseModel
import uvicorn

# ------------------------------------------------------------
# 1.  Import TeamManager (works on both old and new builds)
# ------------------------------------------------------------
try:
    # ≥ 0.4.2.3 re‑exports it here
    from autogenstudio import TeamManager
except ImportError:
    # ≤ 0.4.2.2 keeps it in a sub‑module
    from autogenstudio.teammanager import TeamManager   # type: ignore

# ------------------------------------------------------------
# 2.  CLI definition
# ------------------------------------------------------------
cli = typer.Typer(help="Expose an AutoGen‑Studio team as a REST endpoint")

@cli.command()
def serve(
    team_config: Path = typer.Argument(..., exists=True, help="Path to exported team JSON"),
    endpoint: str = typer.Option(
        "/peak-research",
        help="HTTP path for the POST/GET endpoint (must start with '/')"
    ),
    env_file: Path = typer.Option(
        ".env",
        exists=False,
        help="Path to .env with OPENAI_API_KEY, etc."
    ),
    host: str = typer.Option("0.0.0.0"),
    port: int = typer.Option(8000),
    ssl_certfile: Path = typer.Option(
        None, exists=True, help="Path to SSL certificate file (e.g., cert.pem)"
    ),
    ssl_keyfile: Path = typer.Option(
        None, exists=True, help="Path to SSL key file (e.g., key.pem)"
    ),
):
    """
    Start the FastAPI app that fronts the chosen AutoGen‑Studio team.
    """

    # 2‑a. Load env vars (if any) **before** we spin up the team
    env_path = env_file.expanduser().resolve()
    if env_path.is_file():
        load_dotenv(env_path)
    else:
        typer.echo(f"⚠️  Env file '{env_path}' not found – continuing with current environment.")

    # 2‑b. Create a single TeamManager instance we’ll reuse
    tm = TeamManager()

    # --------------------------------------------------------
    # 3.  Build FastAPI surface
    # --------------------------------------------------------
    app = FastAPI(
        title=f"AutoGen wrapper for '{team_config.name}'",
        description="Custom endpoint that runs an AutoGen‑Studio team spec",
        version="1.0.0",
    )

    class PromptIn(BaseModel):
        topic: str

    @app.get(endpoint, summary=f"Run team {team_config.name}")
    async def run_team_get(topic: str):
        """
        Invoke the team on the caller's topic via GET request and return the final reply.
        """
        result = await tm.run(  # Ensure the coroutine is awaited
            task=topic,
            team_config=str(team_config),   # path to JSON spec
        )

        report = result.model_dump()["task_result"]["messages"][-1]["content"]
        # Remove the final "TERMINATE" string generated by the AI agents
        report = report.rstrip("TERMINATE").strip()

        #return {"answer": result}
        return {"summary": report}

#    @app.post(endpoint, summary=f"Run team {team_config.name}")
#    async def run_team_post(body: PromptIn):
#        """
#        Invoke the team on the caller's topic via POST request and return the final reply.
#        """
#        result = await tm.run(  # Ensure the coroutine is awaited
#            task=body.topic,
#            team_config=str(team_config),   # path to JSON spec
#        )
#
#        report = result.model_dump()["task_result"]["messages"][-1]["content"]
#        # Remove the final "TERMINATE" string generated by the AI agents
#        report = report.rstrip("TERMINATE").strip()
#
#        #return {"answer": result}
#        return {"summary": report}

    # --------------------------------------------------------
    # 4.  Launch the HTTP server
    # --------------------------------------------------------
    uvicorn.run(
        app,
        host=host,
        port=port,
        ssl_certfile=str(ssl_certfile) if ssl_certfile else None,
        ssl_keyfile=str(ssl_keyfile) if ssl_keyfile else None,
    )

# ------------------------------------------------------------
# 5.  Entrypoint
# ------------------------------------------------------------
if __name__ == "__main__":

    # Filter out Autogen's warning about loading teams from a config file 
    warnings.filterwarnings("ignore", message="\n⚠️  SECURITY WARNING ⚠️\n"
                "Loading a FunctionTool from config will execute code to import the provided global imports and and function code.\n"
                "Only load configs from TRUSTED sources to prevent arbitrary code execution.")

    cli()

