#!/usr/bin/env python3

import os
import argparse
import json
import asyncio
import re
from pathlib import Path
import warnings
from dotenv import load_dotenv
from openai import OpenAI
from markdown_pdf import MarkdownPdf, Section
from autogenstudio.teammanager import TeamManager 
from markdownify import markdownify as md_to_text

def find_dotenv_file():
    """Search for a .env file in current directory and parent directories"""
    current_dir = Path.cwd()
    while current_dir != current_dir.parent:  # Stop at root directory
        env_path = current_dir / '.env'
        if env_path.exists():
            return str(env_path)
        current_dir = current_dir.parent
    return None  # No .env file found

def generate_unique_filename(title, extension):
    """Generate a unique filename based on the title and extension."""
    sanitized_title = re.sub(r'[^a-zA-Z0-9_]', '_', title.lower().strip())
    base_filename = f"{sanitized_title}{extension}"
    counter = 0

    while os.path.exists(base_filename):
        counter += 1
        base_filename = f"{sanitized_title} ({counter}){extension}"

    return base_filename

# Filter out Autogen's warning about loading teams from a config file 
warnings.filterwarnings("ignore", message="\n⚠️  SECURITY WARNING ⚠️\n"
            "Loading a FunctionTool from config will execute code to import the provided global imports and and function code.\n"
            "Only load configs from TRUSTED sources to prevent arbitrary code execution.")

# Set up argument parser
parser = argparse.ArgumentParser(description='Generate a threat hunting report for a specific technique')
parser.add_argument('-t', '--technique', required=True, help='The cybersecurity technique to research')
parser.add_argument('-e', '--environment', help='Path to specific .env file to use')
parser.add_argument('-j', '--json', help='Path to JSON file for team configuration', default='team.json')
parser.add_argument('-f', '--format', choices=['pdf', 'markdown'], default='markdown', help='Output report format: pdf or markdown')
args = parser.parse_args()

# Load environment variables
if args.environment:
    # Use the specified .env file
    dotenv_path = args.environment
    if not os.path.exists(dotenv_path):
        print(f"Error: Specified environment file '{dotenv_path}' not found")
        exit(1)
    load_dotenv(dotenv_path)
else:
    # Search for .env file
    dotenv_path = find_dotenv_file()
    if dotenv_path:
        load_dotenv(dotenv_path)
    else:
        print("Warning: No .env file found in current or parent directories")

# Initialize the TeamManager
manager = TeamManager()

async def fetch_report():
    result = await manager.run(
        task=args.technique,
        team_config=args.json,   # path to JSON spec
    )

    report = result.model_dump()["task_result"]["messages"][-1]["content"]

    return report

if __name__ == "__main__":
    report = asyncio.run(fetch_report())

    # Remove the final "TERMINATE" string generated by the AI agents
    report = re.sub(r'\s*TERMINATE\s*$', '', report).strip()

    # Extract the title from the report (assuming the first line is the title)
    title = report.splitlines()[0] if report else "untitled_report"

    # Remove any markdown or extraneous whitespace from the title
    title = re.sub(r'^[#\s]+', '', title).strip()  # Sanitize the title

    # Determine the file extension based on the selected format
    if args.format == 'pdf':
        extension = '.pdf'
    elif args.format == 'markdown':
        extension = '.md'

    filename = generate_unique_filename(title, extension)

    # Save the report in the selected format
    if args.format == 'pdf':
        pdf = MarkdownPdf(toc_level=1)
        pdf.add_section(Section(report))
        pdf.save(filename)
    else:
        with open(filename, 'w') as file:
            file.write(report)

    print(f"Report saved as {filename}")

